apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.name }}-postgres
data:
  postgresUser: {{ .Values.postgres.user | quote }}
  postgresPassword: {{ .Values.postgres.password | default "sdflkj"}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.name }}-postgres
spec:
  selector:
    matchLabels:g
      kubernetes.io/app: {{ .Release.name }}-postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        kubernetes.io/app: {{ .Release.name }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdb"
          - name: POSTGRES_USER
            value: {{ .Values.postgres.user | quote }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgres.password | quote }}